clear all
close all

%R_g_star = 0.00122;
R_g_star = 0.00252;
xi_tilde = -0.161741546491008;
xi_tilde1 = 0.368279374538046;

N = 1000;
phi = 0;



%[xi_tilde,xi_tilde1] = Rootfinder_xi_xi1(R_g_star,N,-10.191);
[Qv00,Ql00,Qv01,Ql01] = A_FullMassFlowRate(xi_tilde,xi_tilde1,R_g_star,N);
[z,delta_p0,pl0,pv0] = ZPlots(R_g_star,phi);
[Qv0,caplimit] = Rootfinder_Qv0(phi,xi_tilde,xi_tilde1,Qv00,Qv01,false,R_g_star,1.7991);
% [Qv0_zero,caplimit_zero] = Rootfinder_Qv0(phi,xi_tilde,xi_tilde1,Qv00,Qv01,true,R_g_star);

g = 9.81;

%pipe geometry
Ng = 26;
t_p = 2*pi/Ng;
t_g = 7.9*pi/180;
R_l = 1/t_p;
R_g = R_g_star*Ng/(2*pi*0.001091);
R_l_star = 0.001091;
R = R_l_star/R_g_star;
P_star = t_p*R_l_star;
Aw_star = pi*(R_g_star^2-R_l_star^2); %m^2

%lengths in meters
Le_star = 0.1;
La_star = 0.1;
Lc_star = 0.095;
Leff_star = La_star + (Le_star + Lc_star)/2;
Lt_star = Le_star + La_star + Lc_star;

epsilon = P_star/La_star;

%physical properties of water/pipe @60C
rho_v = 0.1304; %kg/m^3
rho_l = 983.2;
rho_tilde = rho_v/rho_l;
mu_v = 1.085*10^-5; %kg/(m*s)
mu_l = 4.660*10^-4;
mu_tilde = mu_v/mu_l;
h_lv = 2.358*10^6; %J/kg
sigma = 0.06624; %N/m
K = 3.95*10^-10; %permeability of wick
dpc_star_max = 765; %Pa
p_sat_star = 19950; %Pa
V_sv_star = dpc_star_max*P_star*epsilon/mu_v;
Ca_hat = dpc_star_max*P_star/sigma;
delta_Bo = (rho_l-rho_v)*g*La_star*sin(phi)/dpc_star_max;

%nondim

Le = Le_star/La_star;
Lc = Lc_star/La_star;
Aw = Aw_star*K/(P_star^4);


%% Case A
ze_star = linspace(-Le_star,0,100);
za_star = linspace(0,La_star,100);
zc_star = linspace(La_star,La_star+Lc_star,100);

qc_star_A = (dpc_star_max - (rho_v - rho_l)*g*sin(phi)*Lt_star)/...
    (8*mu_v*Leff_star/(pi*rho_v*R_l_star^4*h_lv)+...
    mu_l*Leff_star/(K*rho_l*Aw_star*h_lv));
delta_p_vt_A = 8*mu_v*qc_star_A*Leff_star/(pi*rho_v*R_l_star^4*h_lv)+...
    rho_v*g*sin(phi)*Lt_star;

p_ve_star_A = p_sat_star - 8*mu_v*qc_star_A/(pi*rho_v*R_l_star^4*h_lv)*...
    (ze_star.^2/(2*Le_star)+ze_star+Le_star/2) - rho_v*g*sin(phi)*...
    (Le_star+ze_star);
p_va_star_A = p_sat_star - 8*mu_v*qc_star_A/(pi*rho_v*R_l_star^4*h_lv)*...
    (za_star+Le_star/2) - rho_v*g*sin(phi)*(Le_star+za_star);
p_vc_star_A = p_sat_star - 8*mu_v*qc_star_A/(pi*rho_v*R_l_star^4*h_lv)*...
    (Le_star/2+La_star+(zc_star-La_star).*(La_star+2*Lc_star-zc_star)/...
    (2*Lc_star)) - rho_v*g*sin(phi)*(Le_star+zc_star);

p_le_star_A = p_sat_star - delta_p_vt_A + ...
    mu_l*qc_star_A/(K*rho_l*Aw_star*h_lv)*...
    (ze_star.^2/(2*Le_star) + ze_star - Lc_star/2 - La_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - ze_star);
p_la_star_A = p_sat_star - delta_p_vt_A + ...
    mu_l*qc_star_A/(K*rho_l*Aw_star*h_lv)*...
    (za_star - Lc_star/2 - La_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - za_star);
p_lc_star_A = p_sat_star - delta_p_vt_A - ...
    mu_l*qc_star_A/(K*rho_l*Aw_star*h_lv)*...
    (La_star + Lc_star - zc_star).^2/(2*Lc_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - zc_star);

z_star = [ze_star za_star zc_star];
p_v_star_A = [p_ve_star_A p_va_star_A p_vc_star_A];
p_l_star_A = [p_le_star_A p_la_star_A p_lc_star_A];

plot(z_star,p_v_star_A,'r','LineWidth',1);
hold on
plot(z_star,p_l_star_A,'r','LineWidth',1);

%Case B
n = (0:N-1);
m = (1:2*N);
gamma = pi*(1+2*n)/t_g;
beta = ((m - 1/2)*pi / log(1/R));
Bm_hat = (4*R_g^2*log(R)*beta-(2*R_l^2*log(R)*beta.^2+...
    (R_g^2-R_l^2)*(4+beta.^2)).*(-1).^m)./...
    (2*beta.^2.*(4+beta.^2)*(log(R))^2);

K1 = (t_g/32)*(R_l^4-R_g^4-(R_g^2-R_l^2)^2/log(R));
K2_terms = -Bm_hat.*... 
    ((2*R_l^2*(-1).^m + beta*R_g^2).*tanh(beta*t_g/2))./...
    (beta.*(4+beta.^2)); %updated to reflect sin and cos simplifications
K2 = sum(K2_terms);

Cn_star = 4*(-1).^n./(R_l_star.^(gamma-1) + ...
    R_g_star.^(2*gamma).*R_l_star.^(-gamma-1))*t_g;
K1_star = K1*P_star^4;
K2_star = K2*P_star^4;
%multiplied by R^gamma/R^gamma to fix NaN issue:
K4_star_terms = 4*(-1).^n*R_g_star^3.*(2*gamma.*R.^gamma+R.^(3*gamma+2).*(2-gamma)...
    -R.^2*(2+gamma))./(t_g*gamma.^3.*(gamma.^2-4).*...
    (R.^(2*gamma-1)+R.^(-1)));
K4_star = sum(K4_star_terms);
Ca = R_l/2 + (R_l^2-R_g^2)/(4*R_l*log(1/R));
Ca_star = P_star^2*Ca;

qc_star_B = (dpc_star_max - (rho_v - rho_l)*g*sin(phi)*Lt_star)/...
    (Leff_star*(8*mu_v/(pi*rho_v*R_l_star^4*h_lv)+...
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv)-1/(2*Ng*rho_l*h_lv))/...
    (K1_star + K2_star - Ca_star*K4_star)*mu_l));
delta_p_vt_B = 8*mu_v*qc_star_B*Leff_star/(pi*rho_v*R_l_star^4*h_lv)+...
    rho_v*g*sin(phi)*Lt_star; %is this right???

p_ve_star_B = p_sat_star - 8*mu_v*qc_star_B/(pi*rho_v*R_l_star^4*h_lv)*...
    (ze_star.^2/(2*Le_star)+ze_star+Le_star/2) - rho_v*g*sin(phi)*...
    (Le_star+ze_star);
p_va_star_B = p_sat_star - 8*mu_v*qc_star_B/(pi*rho_v*R_l_star^4*h_lv)*...
    (za_star+Le_star/2) - rho_v*g*sin(phi)*(Le_star+za_star);
p_vc_star_B = p_sat_star - 8*mu_v*qc_star_B/(pi*rho_v*R_l_star^4*h_lv)*...
    (Le_star/2+La_star+(zc_star-La_star).*(La_star+2*Lc_star-zc_star)/...
    (2*Lc_star)) - rho_v*g*sin(phi)*(Le_star+zc_star);

p_le_star_B = p_sat_star - delta_p_vt_B + ...
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv) - 1/(2*Ng*rho_l*h_lv))...
    *mu_l*qc_star_B/(K1_star + K2_star - Ca_star*K4_star)*...
    (ze_star.^2/(2*Le_star) + ze_star - Lc_star/2 - La_star)+...
    rho_l*g*sin(phi)*(La_star + Lc_star - ze_star);
p_la_star_B = p_sat_star - delta_p_vt_B + ...
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv) - 1/(2*Ng*rho_l*h_lv))...
    *mu_l*qc_star_B/(K1_star + K2_star - Ca_star*K4_star)*...
    (za_star - Lc_star/2 - La_star)+...
    rho_l*g*sin(phi)*(La_star + Lc_star - za_star);
p_lc_star_B = p_sat_star - delta_p_vt_B - ...
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv) - 1/(2*Ng*rho_l*h_lv))...
    *mu_l*qc_star_B/(K1_star + K2_star - Ca_star*K4_star)*...
    (La_star + Lc_star - zc_star).^2/(2*Lc_star)+...
    rho_l*g*sin(phi)*(La_star + Lc_star - zc_star);

p_v_star_B = [p_ve_star_B p_va_star_B p_vc_star_B];
p_l_star_B = [p_le_star_B p_la_star_B p_lc_star_B];

plot(z_star,p_v_star_B,'b');
hold on
plot(z_star,p_l_star_B,'b');

% Case C0

qc_star_C0 = (dpc_star_max - (rho_v - rho_l)*g*sin(phi)*Lt_star)/...
    (4*mu_v*(Le_star+Lc_star)/(pi*rho_v*R_l_star^4*h_lv) + ...
    mu_l*(Le_star+Lc_star)/(2*K*rho_l*Aw_star*h_lv) - ...
    mu_v*La_star/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    mu_l*La_star/(2*Ng*rho_l*h_lv*P_star^4*Ql00));
delta_p_vt_C0 = 4*mu_v*qc_star_C0*(Le_star+Lc_star)/...
    (pi*rho_v*R_l_star^4*h_lv) - La_star*qc_star_C0*mu_v/...
    (2*Ng*rho_v*h_lv*P_star^4*Qv00) + rho_v*g*sin(phi)*Lt_star;

p_ve_star_C0 = p_sat_star - 8*mu_v*qc_star_C0/(pi*rho_v*R_l_star^4*h_lv)*...
    (ze_star.^2/(2*Le_star)+ze_star+Le_star/2) - rho_v*g*sin(phi)*...
    (Le_star+ze_star);
p_va_star_C0 = p_sat_star - ...
    4*mu_v*qc_star_C0*Le_star/(pi*rho_v*R_l_star^4*h_lv) + ...
    za_star*qc_star_C0*mu_v/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    rho_v*g*sin(phi)*(Le_star+za_star);
p_vc_star_C0 = p_sat_star - ...
    4*mu_v*qc_star_C0*Le_star/(pi*rho_v*R_l_star^4*h_lv) + ...
    La_star*qc_star_C0*mu_v/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    8*mu_v*qc_star_C0/(pi*rho_v*R_l_star^4*h_lv)*...
    ((zc_star-La_star).*(La_star+2*Lc_star-zc_star)/(2*Lc_star)) - ...
    rho_v*g*sin(phi)*(Le_star+zc_star);

p_le_star_C0 = p_sat_star - delta_p_vt_C0 - ...
    mu_l*qc_star_C0*Lc_star/(2*K*rho_l*Aw_star*h_lv) + ...
    mu_l*qc_star_C0*La_star/(2*Ng*rho_l*h_lv*P_star^4*Ql00) + ...
    mu_l*qc_star_C0*(ze_star.^2/Le_star+2*ze_star)/(2*K*rho_l*Aw_star*h_lv) + ...
    rho_l*g*sin(phi)*(La_star+Lc_star-ze_star);
p_la_star_C0 = p_sat_star - delta_p_vt_C0 - ...
    mu_l*qc_star_C0*Lc_star/(2*K*rho_l*Aw_star*h_lv) - ...
    mu_l*qc_star_C0*(za_star-La_star)/(2*Ng*rho_l*h_lv*P_star^4*Ql00) + ...
    rho_l*g*sin(phi)*(La_star+Lc_star-za_star);
p_lc_star_C0 = p_sat_star - delta_p_vt_C0 - ...
    mu_l*qc_star_C0/(K*rho_l*Aw_star*h_lv)*...
    (La_star + Lc_star - zc_star).^2/(2*Lc_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - zc_star);

p_v_star_C0 = [p_ve_star_C0 p_va_star_C0 p_vc_star_C0];
p_l_star_C0 = [p_le_star_C0 p_la_star_C0 p_lc_star_C0];

plot(z_star,p_v_star_C0,'g','LineWidth',1);
hold on
plot(z_star,p_l_star_C0,'g','LineWidth',1);

%% Case C1

za_star_C1 = z*La_star;
z_star_C1 = [ze_star za_star_C1 zc_star];

delta_p0_star = delta_p0*dpc_star_max; %dimensional adiabatic pv*-pl*

p_ve_star_C1 = p_sat_star - 8*mu_v*caplimit/(pi*rho_v*R_l_star^4*h_lv)*...
    (ze_star.^2/(2*Le_star)+ze_star+Le_star/2) - rho_v*g*sin(phi)*...
    (Le_star+ze_star);

%above @z=0, i.e. dimensional vapor pressure at beginning of adiabatic
p_ve_star = p_sat_star - 8*mu_v*caplimit/(pi*rho_v*R_l_star^4*h_lv)*...
    (Le_star/2) - rho_v*g*sin(phi)*(Le_star);
p_le_star = p_ve_star-delta_p0_star(1);

pv0_star = pv0*dpc_star_max + p_le_star;
pl0_star = pl0*dpc_star_max + p_le_star;

p_va_star_C1 = pv0_star;


p_vc_star_C1 = pv0_star(end) - 8*mu_v*caplimit/(pi*rho_v*R_l_star^4*h_lv)*...
    ((zc_star-La_star).*(La_star+2*Lc_star-zc_star)/...
    (2*Lc_star)) - rho_v*g*sin(phi)*(Le_star+zc_star);

delta_p_vt_C1 = p_ve_star_C1(1) - p_vc_star_C1(end);

p_lc_star_C1 = p_sat_star - delta_p_vt_C1 - ...
    mu_l*caplimit/(K*rho_l*Aw_star*h_lv)*...
    (La_star + Lc_star - zc_star).^2/(2*Lc_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - zc_star);
p_la_star_C1 = pl0_star;
p_le_star_C1 = pl0_star(1) + ...
    mu_l*caplimit/(K*rho_l*Aw_star*h_lv)*...
    (ze_star.^2/(2*Le_star) + ze_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - ze_star);

p_v_star_C1 = [p_ve_star_C1 p_va_star_C1 p_vc_star_C1];
p_l_star_C1 = [p_le_star_C1 p_la_star_C1 p_lc_star_C1];

plot(z_star_C1,p_v_star_C1,'black--','LineWidth',1);
hold on
plot(z_star_C1,p_l_star_C1,'black--','LineWidth',1);

% Case D0

qc_star_D0 = (dpc_star_max - (rho_v - rho_l)*g*sin(phi)*Lt_star)/...
    (4*mu_v*(Le_star+Lc_star)/(pi*rho_v*R_l_star^4*h_lv) - ...
    mu_v*La_star/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    mu_l*La_star/(2*Ng*rho_l*h_lv*P_star^4*Ql00) + ...
    (mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv)-1/(4*Ng*rho_l*h_lv))*...
    mu_l*(Lc_star+Le_star)/(K1_star+K2_star-Ca_star*K4_star));
delta_p_vt_D0 = 4*mu_v*qc_star_D0*(Le_star+Lc_star)/...
    (pi*rho_v*R_l_star^4*h_lv) - La_star*qc_star_D0*mu_v/...
    (2*Ng*rho_v*h_lv*P_star^4*Qv00) + rho_v*g*sin(phi)*Lt_star;

p_ve_star_D0 = p_sat_star - 8*mu_v*qc_star_D0/(pi*rho_v*R_l_star^4*h_lv)*...
    (ze_star.^2/(2*Le_star)+ze_star+Le_star/2) - rho_v*g*sin(phi)*...
    (Le_star+ze_star);
p_va_star_D0 = p_sat_star - ...
    4*mu_v*qc_star_D0*Le_star/(pi*rho_v*R_l_star^4*h_lv) + ...
    za_star*qc_star_D0*mu_v/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    rho_v*g*sin(phi)*(Le_star+za_star);
p_vc_star_D0 = p_sat_star - ...
    4*mu_v*qc_star_D0*Le_star/(pi*rho_v*R_l_star^4*h_lv) + ...
    La_star*qc_star_D0*mu_v/(2*Ng*rho_v*h_lv*P_star^4*Qv00) - ...
    8*mu_v*qc_star_D0/(pi*rho_v*R_l_star^4*h_lv)*...
    ((zc_star-La_star).*(La_star+2*Lc_star-zc_star)/(2*Lc_star)) - ...
    rho_v*g*sin(phi)*(Le_star+zc_star);

p_le_star_D0 = p_sat_star - delta_p_vt_D0 + ...
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv) - 1/(2*Ng*rho_l*h_lv))...
    *mu_l*qc_star_D0/(K1_star + K2_star - Ca_star*K4_star)*...
    (ze_star.^2/(2*Le_star) + ze_star - Lc_star/2)+...
    qc_star_D0*mu_l*La_star/(2*Ng*rho_l*h_lv*P_star^4*Ql00)+...
    rho_l*g*sin(phi)*(La_star + Lc_star - ze_star);
p_la_star_D0 = p_sat_star - delta_p_vt_D0 - ... %error somewhere here
    (2*mu_tilde*K4_star/(pi*rho_v*R_l_star^3*h_lv) - 1/(2*Ng*rho_l*h_lv))...
    *mu_l*qc_star_D0/(K1_star + K2_star - Ca_star*K4_star)*(Lc_star/2)-...
    qc_star_D0*mu_l*(za_star-La_star)/(2*Ng*rho_l*h_lv*P_star^4*Ql00)+...
    rho_l*g*sin(phi)*(La_star + Lc_star - za_star);
p_lc_star_D0 = p_sat_star - delta_p_vt_D0 - ...
    mu_l*qc_star_D0/(K*rho_l*Aw_star*h_lv)*...
    (La_star + Lc_star - zc_star).^2/(2*Lc_star) + ...
    rho_l*g*sin(phi)*(La_star + Lc_star - zc_star);

p_v_star_D0 = [p_ve_star_D0 p_va_star_D0 p_vc_star_D0];
p_l_star_D0 = [p_le_star_D0 p_la_star_D0 p_lc_star_D0];

% plot(z_star,p_v_star_D0,'black');
% hold on
% plot(z_star,p_l_star_D0,'black');

xlabel('$z~[\textrm{m}]$','Interpreter','latex','FontSize',18)
ylabel('$\textrm{Pressure}~[\textrm{Pa}]$','Interpreter','latex','FontSize',18)
% legend ('$\mathrm{A}$','','$\mathrm{C_0}$','','$\mathrm{C_1}$','','Interpreter','latex','FontSize',18)